{{- if (eq .Values.database.existingSecret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocsinventory.fullname" . }}
  labels:
    {{- include "ocsinventory.labels" . | nindent 4 }}
type: Opaque
data:
  db-name: {{ required "A db name is required!" .Values.database.database | b64enc | quote }}
  db-user: {{ required "A username is required!" .Values.database.username | b64enc | quote }}
  db-pass: {{ required "A password is required!" .Values.database.password | b64enc | quote }}
  db-host: {{ required "A hostname is required!" .Values.database.hostname | b64enc | quote }}
  {{- if .Values.database.create }}
  root-pass: {{ required "A root password is required!" .Values.database.root_password | b64enc | quote }}
  {{- end }}
  {{- if .Values.ingress.basicauth.enabled }}
  auth: {{ htpasswd (required "A username is required for the basic auth!" .Values.ingress.basicauth.username) (required "A password is required for the basic auth!" .Values.ingress.basicauth.password) | b64enc | quote }}
  {{- end }}
{{- end }}
