apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocsinventory.fullname" . }}
  labels:
    {{- include "ocsinventory.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ipFamilies:
    {{- with .Values.service.ipFamilies }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ocsinventory.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocsinventory.fullname" . }}-apache-metrics
  labels:
    {{- include "ocsinventory.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: metrics
  selector:
    {{- include "ocsinventory.selectorLabels" . | nindent 4 }}
{{- end }}
